### ISSUE TITLE
Ability to collapse "Important Events" in Quests?

### ISSUE THREAD

**Issue by tomasz1986** [r-e-d/LeUI-IWDEE#1]
The BG version of the UI has an ability to collapse quests entries.

IWDEE seems to already collapse quests by default, but the "Important Events" entry always starts uncollapsed. As the entry is usually quite lengthy, it is basically always necessary to scroll down just to be able to see other quests.

Would it be possible to have an option to collapse the "Important Events" as well?

![image](https://user-images.githubusercontent.com/5626656/100185455-3b4c0580-2f27-11eb-8505-024e4355c536.png)

**Comment by r-e-d** [comment]
v1.8 introduces an in-game options to collapse journal entries by default.
